package com.yourplugin.dynamodb.language

import com.intellij.lang.ASTNode
import com.intellij.lang.ParserDefinition
import com.intellij.lang.PsiParser
import com.intellij.lexer.FlexAdapter
import com.intellij.lexer.Lexer
import com.intellij.openapi.project.Project
import com.intellij.psi.FileViewProvider
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.psi.TokenType
import com.intellij.psi.tree.IFileElementType
import com.intellij.psi.tree.TokenSet
import com.yourplugin.dynamodb.language.psi.DynamoQueryTypes

class DynamoQueryParserDefinition : ParserDefinition {

    companion object {
        val FILE = IFileElementType(DynamoQueryLanguage)
        val WHITE_SPACES: TokenSet = TokenSet.create(TokenType.WHITE_SPACE)
        val COMMENTS: TokenSet = TokenSet.create(
            DynamoQueryTypes.LINE_COMMENT,
            DynamoQueryTypes.BLOCK_COMMENT,
        )
        val STRINGS: TokenSet = TokenSet.create(DynamoQueryTypes.STRING)
    }

    override fun createLexer(project: Project): Lexer =
        // Generated lexer is a FlexLexer, so wrap it for IntelliJ's Lexer API.
        FlexAdapter(com.yourplugin.dynamodb.language.lexer.DynamoQueryLexer(null))

    override fun createParser(project: Project): PsiParser =
        // Generated by Grammar-Kit — will exist after `./gradlew generateParser`
        com.yourplugin.dynamodb.language.parser.DynamoQueryParser()

    override fun getFileNodeType() = FILE
    override fun getWhitespaceTokens() = WHITE_SPACES
    override fun getCommentTokens() = COMMENTS
    override fun getStringLiteralElements() = STRINGS

    override fun createElement(node: ASTNode): PsiElement =
        DynamoQueryTypes.Factory.createElement(node)

    override fun createFile(viewProvider: FileViewProvider): PsiFile =
        DynamoQueryFile(viewProvider)
}
